### ISSUE TITLE
Documentation for Google Support Doesn't Work

### ISSUE THREAD

**Issue by stauffec** [stormpath/stormpath-flask#39]
In the documentation, it is recommended that you create a new google app, and that you enter in 2 redirect urls, one for local.domain.com:5000/google, and one for the real domain: www.domain.com/google

However, if I test locally first, then stormpath creates a directory called App-Google. However, it stores the local redirect path. Then, when you try the real thing in production, you get a 400 internal error because I think it tries to use the local.domain.com:5000 redirect url.

Is the answer that you must use 2 different applications?

**Comment by rdegges** [comment]
What you'll need to do when you move your application into production is go into the Stormpath dashboard and update your URI for your directory to the 'live' one.

You'll still want to leave both of those domains (local / production) in your Google app config -- this way you can test locally and in production.

On the Stormpath side, however, only one can be supported at a time (because we can only redirect the user to ONE url at a time), so if you want to do local testing AND run an app in production concurrently, then yes -- you do need two separate applications.

I'll try to find a way to make this more clear in the docs.
