### ISSUE TITLE
Does the password not hashed before sending to stormpath?

### ISSUE THREAD

**Issue by tim-hub** [stormpath/stormpath-flask#86]
It seemed that the flask stormpath not import any encryption tools?

I am not sure. But I did not find it.

**Comment by rdegges** [comment]
This is correct -- the way Stormpath works is that network requests to our service are sent over SSL w/ digest authentication that prevents things like TCP replay attacks, MITM, and a variety of other packet-based attacks.

When an account is created with a password, the password is sent to Stormpath using the digest auth over SSL, where we then hash the passwords.

The reason we do this is so that over time, we can UPGRADE the password hashes to a stronger format (eg: a stronger bcrypt work factor, scrypt, etc.).
